-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."user"
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    password character varying(128) COLLATE pg_catalog."default" NOT NULL,
    first_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone,
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.address
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 ),
    city character varying(50) NOT NULL,
    street character varying(150) NOT NULL,
    building character varying(10) NOT NULL,
    apartment character varying(10),
    region_id integer,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.region
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 ),
    region_name character varying(50),
    PRIMARY KEY (id),
    UNIQUE (region_name)
);

CREATE TABLE IF NOT EXISTS public.user_address
(
    user_id integer,
    address_id integer,
    is_default boolean,
    PRIMARY KEY (user_id, address_id)
);

CREATE TABLE IF NOT EXISTS public.record
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 ),
    title character varying(150) NOT NULL,
    description text,
    image_url character varying(150),
    release_date date NOT NULL,
    duration_seconds integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.artist
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 ),
    name character varying(50) NOT NULL,
    description text,
    image_url character varying(150),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.format
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 ),
    format_name character varying(50) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (format_name)
);

CREATE TABLE IF NOT EXISTS public.product
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 ),
    record_id integer NOT NULL,
    format_id integer NOT NULL,
    description text,
    quantity integer NOT NULL,
    price money NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.discount
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 ),
    product_id integer NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,
    discount_percent integer,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.artist_record
(
    artist_id integer NOT NULL,
    record_id integer NOT NULL,
    PRIMARY KEY (artist_id, record_id)
);

CREATE TABLE IF NOT EXISTS public.genre
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 ),
    name character varying NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.genre_record
(
    genre_id integer NOT NULL,
    record_id integer NOT NULL,
    PRIMARY KEY (genre_id, record_id)
);

CREATE TABLE IF NOT EXISTS public.genre_artist
(
    genre_id integer NOT NULL,
    artist_id integer NOT NULL,
    PRIMARY KEY (genre_id, artist_id)
);

CREATE TABLE IF NOT EXISTS public.track
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 ),
    title character varying NOT NULL,
    duration_seconds integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.track_record
(
    track_id integer NOT NULL,
    record_id integer NOT NULL,
    track_order integer NOT NULL,
    PRIMARY KEY (track_id, record_id)
);

CREATE TABLE IF NOT EXISTS public.track_artist
(
    track_id integer NOT NULL,
    artist_id integer NOT NULL,
    PRIMARY KEY (track_id, artist_id)
);

CREATE TABLE IF NOT EXISTS public.shopping_cart
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 ),
    user_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.shopping_cart_product
(
    shopping_cart_id integer NOT NULL,
    product_id integer NOT NULL,
    quantity integer,
    PRIMARY KEY (shopping_cart_id, product_id)
);

CREATE TABLE IF NOT EXISTS public.shop_order
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 ),
    user_id integer NOT NULL,
    total money NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    city character varying(50) NOT NULL,
    street character varying(150) NOT NULL,
    building character varying(10) NOT NULL,
    apartment character varying(10),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.order_line
(
    shop_order_id integer NOT NULL,
    product_id integer NOT NULL,
    quantity integer NOT NULL,
    price money NOT NULL,
    PRIMARY KEY (shop_order_id, product_id)
);

CREATE TABLE IF NOT EXISTS public.review
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 ),
    user_id integer NOT NULL,
    rating integer NOT NULL,
    description text,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.address
    ADD CONSTRAINT address_region_id_fkey FOREIGN KEY (region_id)
    REFERENCES public.region (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.user_address
    ADD FOREIGN KEY (user_id)
    REFERENCES public."user" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.user_address
    ADD FOREIGN KEY (address_id)
    REFERENCES public.address (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.product
    ADD FOREIGN KEY (record_id)
    REFERENCES public.record (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.product
    ADD FOREIGN KEY (format_id)
    REFERENCES public.format (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.discount
    ADD FOREIGN KEY (product_id)
    REFERENCES public.product (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.artist_record
    ADD FOREIGN KEY (artist_id)
    REFERENCES public.artist (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.artist_record
    ADD FOREIGN KEY (record_id)
    REFERENCES public.record (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.genre_record
    ADD FOREIGN KEY (genre_id)
    REFERENCES public.genre (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.genre_record
    ADD FOREIGN KEY (record_id)
    REFERENCES public.record (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.genre_artist
    ADD FOREIGN KEY (genre_id)
    REFERENCES public.genre (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.genre_artist
    ADD FOREIGN KEY (artist_id)
    REFERENCES public.artist (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.track_record
    ADD FOREIGN KEY (track_id)
    REFERENCES public.track (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.track_record
    ADD FOREIGN KEY (record_id)
    REFERENCES public.record (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.track_artist
    ADD FOREIGN KEY (track_id)
    REFERENCES public.track (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.track_artist
    ADD FOREIGN KEY (artist_id)
    REFERENCES public.artist (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.shopping_cart
    ADD FOREIGN KEY (user_id)
    REFERENCES public."user" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.shopping_cart_product
    ADD FOREIGN KEY (shopping_cart_id)
    REFERENCES public.shopping_cart (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.shopping_cart_product
    ADD FOREIGN KEY (product_id)
    REFERENCES public.product (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.shop_order
    ADD FOREIGN KEY (user_id)
    REFERENCES public."user" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.order_line
    ADD FOREIGN KEY (shop_order_id)
    REFERENCES public.shop_order (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.order_line
    ADD FOREIGN KEY (product_id)
    REFERENCES public.product (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.review
    ADD FOREIGN KEY (user_id)
    REFERENCES public."user" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;